docs: Update twilight_http example, add alt docker build cmd with metrics enabled
twilight-rs/http-proxy pull request #14
Opened 2021-03-23 06:04 UTC by drklee3

### Description

Updates the twilight_http example on the README.  Also adds a `docker build` command with metrics enabled. 

### Tested

Example now compiles on `twilight_http v0.3.5`

2021-03-23 14:37 UTC, Gelbpunkt requested changes
We should probably remove the docker build part from the README and replace it with a reference to the prebuilt ones (`docker.io/twilightrs/http-proxy`).

2021-03-23 14:37 UTC, Gelbpunkt commented on README.md
> +docker run -itd -e DISCORD_TOKEN="my token" -p 3000:80 http-proxy
```suggestion
$ docker build . -t http-proxy
# Or build with the metrics feature enabled
$ docker build . --build-arg FEATURES="expose-metrics" -t http-proxy

$ docker run -itd -e DISCORD_TOKEN="my token" -p 3000:80 http-proxy
```
I'd keep the $ to indicate that this is a shell command and to keep consistency with the part below.

2021-03-23 16:30 UTC, drklee3 commented
> We should probably remove the docker build part from the README and replace it with a reference to the prebuilt ones (`docker.io/twilightrs/http-proxy`).

Ah yeah I was not aware of the prebuilt images, should I just replace the build commands with `docker run .. twilightrs/http-proxy` commands instead?

2021-03-23 16:59 UTC, Gelbpunkt commented
> > We should probably remove the docker build part from the README and replace it with a reference to the prebuilt ones (`docker.io/twilightrs/http-proxy`).
> 
> Ah yeah I was not aware of the prebuilt images, should I just replace the build commands with `docker run .. twilightrs/http-proxy` commands instead?

Yes, that makes more sense. If you do so make sure to mention the different tags for metrics, ARM, API v8 and the old v6.

2021-03-23 21:24 UTC, Gelbpunkt approved these changes

2021-03-24 22:03 UTC, 7596ff requested changes
Thanks for the PR, one small thing:

2021-03-24 22:03 UTC, 7596ff commented on README.md
> +[Docker Hub][docker-hub-tags].
Could you either rename this link to show that it goes to the tags page specially, or use the same link as Docker Hub above?

2021-03-24 22:55 UTC, 7596ff approved these changes

2021-04-11 16:41 UTC, merged