Add support for multiple tokens
twilight-rs/http-proxy pull request #17
Opened 2021-04-27 21:42 UTC by james7132

- Removed the DISCORD_TOKEN default token.
 - Rely on the Authorization header on incoming request to identify which client is which.
 - Allow unauthorized requests to be made with a token-less client. Might be useful when making unauthenticated webhook posts.

Actual separation of monitoring (what #16 requests) will require some identification for each client/token pair.

2021-05-04 21:41 UTC, tbnritzdoge approved these changes

2021-05-04 21:46 UTC, tbnritzdoge requested changes
get bot id from token and serve as a bot_id field in all metrics

the first part of the id (split by ".") is a user id encoded w base64

2021-05-22 18:04 UTC, vivian requested changes

2021-05-22 18:04 UTC, vivian commented on src/main.rs
> +    let clients: ClientMap = Arc::new(DashMap::new());
This implementation will lead to bloat over time because clients are never removed. This needs an expiry on it or needs to be made into an LRU.

2021-05-22 18:04 UTC, vivian commented on src/main.rs
> +    let clients: ClientMap = Arc::new(DashMap::new());
Does this need to be typed? Shouldn't it be inferred by the method call to `handle_request`?

2021-05-22 18:04 UTC, vivian commented on README.md
> +        .token("MY TOKEN")
In this example please use `std::env`; we historically discourage hardcoding in documentation.

2021-08-01 15:19 UTC, closed without merging