expose rate limit scope in metrics
twilight-rs/http-proxy pull request #46
Opened 2021-12-29 08:52 UTC by AEnterprise

exposes the rate limit scopes in the metrics. this allows for separating what rate limit responses could/should have been avoided, from the "unavoidable" ones on shared resources

2021-12-29 14:05 UTC, Gelbpunkt requested changes
can be simplified a tiny bit but looks good to me

2021-12-29 14:05 UTC, Gelbpunkt commented on src/main.rs
> +            .to_string();
```suggestion
        let scope = resp
            .headers()
            .get("X-RateLimit-Scope")
            .and_then(|header| header.to_str().ok())
            .unwrap_or_default()
            .to_string();
```

2021-12-29 14:29 UTC, Gelbpunkt approved these changes

2021-12-30 18:04 UTC, 7596ff approved these changes

2022-01-07 07:48 UTC, Erk- approved these changes

2022-01-07 19:49 UTC, merged