Redo documentation
twilight-rs/http-proxy pull request #51
Opened 2022-01-23 14:35 UTC by Gelbpunkt

Entire revamp of the documentation as explained in the linked issue.

Closes #45

2022-02-11 22:24 UTC, 7596ff requested changes

2022-02-11 22:24 UTC, 7596ff commented on README.md
> +## Using it
```suggestion
## Use
```

2022-02-11 22:24 UTC, 7596ff commented on README.md
> +Discord API.
```suggestion
This proxy is not a "real" HTTP `CONNECT` TCP proxy, it instead mocks the
Discord API.
```

2022-02-11 22:24 UTC, 7596ff commented on README.md
> +In order to use it, change the base URL of all your routes from
I think for this section, we should prefer to begin with explaining the simplest use case, which I understand to be `curl http://localhost:3000/users/@me`. We can then mention that the user can add `/v9/` or another version string to the URL, and be clear whether or not the `/api/` segment is required or optional.

2022-02-11 22:24 UTC, 7596ff commented on README.md
> +twilightrs/http-proxy:metrics
was this meant to be wrapped?

2022-03-13 15:29 UTC, Gelbpunkt commented
Updated, hope I didn't miss anything

2022-03-14 00:32 UTC, 7596ff approved these changes

2022-06-03 07:17 UTC, Erk- approved these changes

2022-06-03 07:19 UTC, merged