fix: insert ratelimiter in map when max_size is not specified
twilight-rs/http-proxy pull request #59
Opened 2022-10-28 14:45 UTC by Siris01

According to the README, the default value for `CLIENT_CACHE_MAX_SIZE` is no limit. This implies that the ratelimiter must be inserted into the dash map when `max_size` is not specified.

2022-10-28 22:33 UTC, 7596ff approved these changes, later dismissed

2022-10-30 15:44 UTC, AEnterprise approved these changes, later dismissed

2022-10-30 16:29 UTC, Erk- approved these changes, later dismissed

2022-10-30 17:01 UTC, Gelbpunkt requested changes

2022-10-30 17:01 UTC, Gelbpunkt commented on src/ratelimiter_map.rs
> +                    if self.max_size.is_none() || self.max_size.filter(|max| max != &0).is_some() {
I'd prefer a `map_or` here:
```suggestion
                    if self.max_size.map_or(true, |max| max != &0) {
 ```

2022-10-30 17:26 UTC, Erk- submitted a review, later dismissed

2022-10-30 17:39 UTC, Gelbpunkt approved these changes

2022-10-30 17:39 UTC, Erk- approved these changes

2022-10-30 18:21 UTC, AEnterprise approved these changes

2022-10-30 21:20 UTC, merged